import DashboardFinanceExpandedSheet from "@/components/fresh/main-dashboard/financial-cards/DashboardFinanceExpandedSheet";

export default function DashboardFinanceExpandedSheetLayer({
  activeDashboardPanel,
  expandedFinanceCard,
  setExpandedFinanceCard,
  walletMoney,
  survivalExpense,
  selectedDashboardTheme,
  expandedFinanceDetailSections,
  toggleExpandedFinanceDetailSection,
  profileData,
  firstPositiveNumber,
  readStoredSurvivalExpense,
  user,
  saveSurvivalExpenseInline,
  wallets,
  walletPreviewTransactions,
  financeActionLoading,
  openCreateWalletModal,
  moveWalletInline,
  openDeleteWalletModal,
  openAddMoneyModal,
  openTransferMoneyModal,
  monthlyBudgetPlan,
  openBudgetModal,
  openDeleteBudgetCategoryModal,
  openResetBudgetModal,
  savingsGoals,
  totalSavingsSaved,
  totalSavingsTarget,
  primarySavingsGoal,
  openSavingsGoalModal,
  openDeleteSavingsGoalModal,
  openAddSavingsModal,
}) {
  return (
    <DashboardFinanceExpandedSheet
      activeDashboardPanel={activeDashboardPanel}
      expandedFinanceCard={expandedFinanceCard}
      setExpandedFinanceCard={setExpandedFinanceCard}
      walletMoney={walletMoney}
      survivalExpense={survivalExpense}
      selectedDashboardTheme={selectedDashboardTheme}
      expandedFinanceDetailSections={expandedFinanceDetailSections}
      toggleExpandedFinanceDetailSection={toggleExpandedFinanceDetailSection}
      profileData={profileData}
      firstPositiveNumber={firstPositiveNumber}
      readStoredSurvivalExpense={readStoredSurvivalExpense}
      user={user}
      onSurvivalSaved={saveSurvivalExpenseInline}
      wallets={wallets}
      walletPreviewTransactions={walletPreviewTransactions}
      financeActionLoading={financeActionLoading}
      openCreateWalletModal={openCreateWalletModal}
      moveWalletInline={moveWalletInline}
      openDeleteWalletModal={openDeleteWalletModal}
      openAddMoneyModal={openAddMoneyModal}
      openTransferMoneyModal={openTransferMoneyModal}
      monthlyBudgetPlan={monthlyBudgetPlan}
      openBudgetModal={openBudgetModal}
      openDeleteBudgetCategoryModal={openDeleteBudgetCategoryModal}
      openResetBudgetModal={openResetBudgetModal}
      savingsGoals={savingsGoals}
      totalSavingsSaved={totalSavingsSaved}
      totalSavingsTarget={totalSavingsTarget}
      primarySavingsGoal={primarySavingsGoal}
      openSavingsGoalModal={openSavingsGoalModal}
      openDeleteSavingsGoalModal={openDeleteSavingsGoalModal}
      openAddSavingsModal={openAddSavingsModal}
    />
  );
}
