export const createInitialFinanceForm = () => ({
  name: "",
  type: "cash",
  customWalletType: "",
  startingBalance: "0",
  amount: "",
  destinationWalletId: "",
  expenseWalletId: "",
  budgetListKey: "",
  unplannedReason: "",
  undocumentedReason: "",
  undocumentedNote: "",
  totalBudget: "",
  monthlyBudgetAmount: "",
  needsPct: "50",
  wantsPct: "30",
  otherPct: "20",
  title: "",
  budgetCategoryName: "",
  targetAmount: "",
  savingsWalletId: "",
  category: "",
  subcategory: "",
  plannedUseDate: "",
  reasonOne: "",
  reasonTwo: "",
  reasonThree: "",
  emotionalValue: "joy",
  priority: "medium",
  flexibility: "flexible",
  notes: "",
});

export default createInitialFinanceForm;
