from pathlib import Path

TARGET = Path('src/runtime/installClaraOrbGreeting.js')

source = TARGET.read_text()
marker = 'MEANS_COMPLETED_SAVINGS_FILTER_V1'

# Preserve the existing production compatibility filter while Phase 1 proves
# the exact stale Savings Goal record. This is intentionally not the final
# lifecycle authority; the permanent fix must move into canonical app source.
if marker not in source:
    old = '''    const status = normalizeLower(goal?.status);\n    const inactive = Boolean(\n      goal?.deletedAt ||\n        goal?.deleted_at ||\n        goal?.isArchived === true ||\n        goal?.is_archived === true ||\n        [\"deleted\", \"archived\", \"cancelled\", \"canceled\"].includes(status)\n    );'''
    new = '''    const status = normalizeLower(\n      goal?.completion_status || goal?.completionStatus || goal?.status\n    );\n    const inactive = Boolean(\n      goal?.deletedAt ||\n        goal?.deleted_at ||\n        goal?.completedAt ||\n        goal?.completed_at ||\n        goal?.isArchived === true ||\n        goal?.is_archived === true ||\n        [\n          \"completed\",\n          \"complete\",\n          \"fulfilled\",\n          \"consumed\",\n          \"deleted\",\n          \"archived\",\n          \"cancelled\",\n          \"canceled\",\n        ].includes(status)\n    ); // MEANS_COMPLETED_SAVINGS_FILTER_V1'''
    if old not in source:
        raise SystemExit('Means Score Savings Goal inactive filter anchor missing')
    source = source.replace(old, new, 1)

instrument_marker = 'CLARA_MEANS_SAVINGS_INPUT_V1'
if instrument_marker not in source:
    input_anchor = '''  ]);\n  const payCycle = resolveMeansPayCycle(incomeSources);'''
    input_instrumented = '''  ]);\n  console.log(\"[CLARA MEANS] SAVINGS INPUT\", (Array.isArray(savingsGoals) ? savingsGoals : []).map((goal) => ({\n    id: goal?.id,\n    title: goal?.title || goal?.name,\n    target:\n      goal?.target_amount ??\n      goal?.targetAmount ??\n      goal?.target,\n    saved:\n      goal?.saved_amount ??\n      goal?.savedAmount ??\n      goal?.current_amount ??\n      goal?.currentAmount,\n    status: goal?.status,\n    completion_status:\n      goal?.completion_status ??\n      goal?.completionStatus,\n    completedAt:\n      goal?.completedAt ??\n      goal?.completed_at,\n    deletedAt:\n      goal?.deletedAt ??\n      goal?.deleted_at,\n    archived:\n      goal?.archived ??\n      goal?.is_archived,\n    planned_use_date:\n      goal?.planned_use_date ??\n      goal?.plannedUseDate,\n    activity:\n      goal?.savingsActivityLog ??\n      goal?.savings_activity_log ??\n      goal?.activityLog ??\n      goal?.activity_log,\n    source: goal?.source,\n  }))); // CLARA_MEANS_SAVINGS_INPUT_V1\n  const payCycle = resolveMeansPayCycle(incomeSources);'''
    if input_anchor not in source:
        raise SystemExit('Means Score Savings input instrumentation anchor missing')
    source = source.replace(input_anchor, input_instrumented, 1)

    old_function = '''function futureSavingsGoalAmount(goals = [], horizonEnd = endOfCurrentMonthKey()) {\n  const today = localDateKey();\n\n  return (Array.isArray(goals) ? goals : []).reduce((sum, goal) => {\n    const status = normalizeLower(\n      goal?.completion_status || goal?.completionStatus || goal?.status\n    );\n    const inactive = Boolean(\n      goal?.deletedAt ||\n        goal?.deleted_at ||\n        goal?.completedAt ||\n        goal?.completed_at ||\n        goal?.isArchived === true ||\n        goal?.is_archived === true ||\n        [\n          \"completed\",\n          \"complete\",\n          \"fulfilled\",\n          \"consumed\",\n          \"deleted\",\n          \"archived\",\n          \"cancelled\",\n          \"canceled\",\n        ].includes(status)\n    ); // MEANS_COMPLETED_SAVINGS_FILTER_V1\n    if (inactive) return sum;\n\n    const date = savingsGoalDate(goal);\n    if (!date || date <= today || date >= horizonEnd) return sum;\n\n    const target = savingsGoalMoney(\n      goal?.target_amount,\n      goal?.targetAmount,\n      goal?.goal_amount,\n      goal?.goalAmount,\n      goal?.target,\n      goal?.amount\n    );\n    const saved = savingsGoalMoney(\n      goal?.saved_amount,\n      goal?.savedAmount,\n      goal?.current_amount,\n      goal?.currentAmount,\n      goal?.saved,\n      goal?.progress_amount,\n      goal?.progressAmount,\n      goal?.amount_saved\n    );\n\n    return sum + Math.max(target - saved, 0);\n  }, 0);\n}'''
    new_function = '''function futureSavingsGoalAmount(goals = [], horizonEnd = endOfCurrentMonthKey()) {\n  const today = localDateKey();\n\n  const total = (Array.isArray(goals) ? goals : []).reduce((sum, goal) => {\n    const status = normalizeLower(\n      goal?.completion_status || goal?.completionStatus || goal?.status\n    );\n    const inactive = Boolean(\n      goal?.deletedAt ||\n        goal?.deleted_at ||\n        goal?.completedAt ||\n        goal?.completed_at ||\n        goal?.isArchived === true ||\n        goal?.is_archived === true ||\n        [\n          \"completed\",\n          \"complete\",\n          \"fulfilled\",\n          \"consumed\",\n          \"deleted\",\n          \"archived\",\n          \"cancelled\",\n          \"canceled\",\n        ].includes(status)\n    ); // MEANS_COMPLETED_SAVINGS_FILTER_V1\n    if (inactive) return sum;\n\n    const date = savingsGoalDate(goal);\n    if (!date || date <= today || date >= horizonEnd) return sum;\n\n    const target = savingsGoalMoney(\n      goal?.target_amount,\n      goal?.targetAmount,\n      goal?.goal_amount,\n      goal?.goalAmount,\n      goal?.target,\n      goal?.amount\n    );\n    const saved = savingsGoalMoney(\n      goal?.saved_amount,\n      goal?.savedAmount,\n      goal?.current_amount,\n      goal?.currentAmount,\n      goal?.saved,\n      goal?.progress_amount,\n      goal?.progressAmount,\n      goal?.amount_saved\n    );\n    const remaining = Math.max(target - saved, 0);\n    const activity =\n      goal?.savingsActivityLog ??\n      goal?.savings_activity_log ??\n      goal?.activityLog ??\n      goal?.activity_log ??\n      [];\n    console.log(\"[CLARA MEANS] SAVINGS ACCEPTED\", {\n      id: goal?.id,\n      title: goal?.title || goal?.name,\n      target,\n      saved,\n      remaining,\n      status: goal?.status,\n      completion_status: goal?.completion_status ?? goal?.completionStatus,\n      completedAt: goal?.completedAt ?? goal?.completed_at,\n      deletedAt: goal?.deletedAt ?? goal?.deleted_at,\n      activityTypes: Array.isArray(activity)\n        ? activity.map((entry) => String(entry?.type || \"\").trim().toLowerCase()).filter(Boolean)\n        : [],\n      reasonAccepted: \"active_by_current_means_filter_and_inside_cycle_horizon\",\n    });\n\n    return sum + remaining;\n  }, 0);\n\n  console.log(\"[CLARA MEANS] SAVINGS TOTAL\", total);\n  return total;\n}'''
    if old_function not in source:
        raise SystemExit('Means Score Savings accepted instrumentation anchor missing')
    source = source.replace(old_function, new_function, 1)

TARGET.write_text(source)
print('Means Score Savings Goal Phase 1 instrumentation patched')
