export const createEmptyDashboardCache = (key = null) => ({
  key,
  loaded: false,
  tasks: [],
  submissions: [],
  programRecord: null,
  survivalExpense: 0,
  walletMoney: 0,
  wallets: [],
  walletTransactions: [],
  budgets: [],
  savingsGoals: [],
  expenses: [],
  pendingExpenses: [],
  offlineReady: false,
  profileData: null,
  latestEnrollment: null,
  guardChecked: false,
  nickname: "",
  reminderTime: "",
  financialGoal: "",
});
