export const learningHubCategories = [
  {
    id: "money-foundations",
    type: "youtube",
    title: "Money Foundations",
    badge: "WATCH FIRST",
    contentTypeLabel: "Curated Video Lessons",
    sourceType: "youtube",
    subtitle: "Build the basics before you budget, save, or spend.",
    thumbnail: "/learning-hub/money-foundations/category.png",
    description: "A curated CLARA learning path that builds the money basics before budgeting, saving, or spending.",
    order: 0,
    ctaLabel: "Start watching",
    lessons: [
      {
        id: "whole-map-of-money",
        lessonNumber: 1,
        title: "The Whole Map of Money",
        subtitle: "See how income, spending, debt, savings, and investing all connect.",
        thumbnail: "/learning-hub/money-foundations/lesson-01.png",
        youtubeId: "mnuOZcmoGD8",
        sourceUrl: "https://www.youtube.com/watch?v=mnuOZcmoGD8&t=2s",
      },
      {
        id: "money-is-psychological-first",
        lessonNumber: 2,
        title: "Money Is Psychological First",
        subtitle: "Understand how behavior, emotion, patience, and mindset shape your money.",
        thumbnail: "/learning-hub/money-foundations/lesson-02.png",
        youtubeId: "uWWEodOlDGk",
        sourceUrl: "https://www.youtube.com/watch?v=uWWEodOlDGk",
      },
      {
        id: "assets-vs-liabilities",
        lessonNumber: 3,
        title: "Assets vs Liabilities",
        subtitle: "Learn the difference between what builds wealth and what drains it.",
        thumbnail: "/learning-hub/money-foundations/lesson-03.png",
        youtubeId: "5yxuplSm1WQ",
        sourceUrl: "https://youtu.be/5yxuplSm1WQ?si=Ah9zLf7hJk1US33W",
      },
      {
        id: "wealth-is-built-by-rules",
        lessonNumber: 4,
        title: "Wealth Is Built by Rules",
        subtitle: "Strong money habits grow when you follow simple, repeatable rules.",
        thumbnail: "/learning-hub/money-foundations/lesson-04.png",
        youtubeId: "Pd3HYjpmks4",
        sourceUrl: "https://www.youtube.com/watch?v=Pd3HYjpmks4&t=9s",
      },
      {
        id: "millionaire-habits",
        lessonNumber: 5,
        title: "Millionaire Habits",
        subtitle: "Wealth often grows through quiet discipline, not flashy spending.",
        thumbnail: "/learning-hub/money-foundations/lesson-05.png",
        youtubeId: "dVSmsRK6Cck",
        sourceUrl: "https://www.youtube.com/watch?v=dVSmsRK6Cck&t=39s",
      },
      {
        id: "investing-without-gambling",
        lessonNumber: 6,
        title: "Investing Without Gambling",
        subtitle: "Build wealth through patience, value, and risk control.",
        thumbnail: "/learning-hub/money-foundations/lesson-06.png",
        youtubeId: "KJSSvOY1UOk",
        sourceUrl: "https://www.youtube.com/watch?v=KJSSvOY1UOk&t=149s",
      },
      {
        id: "financial-freedom-needs-systems",
        lessonNumber: 7,
        title: "Financial Freedom Needs Systems",
        subtitle: "A system beats willpower when saving, budgeting, and investing.",
        thumbnail: "/learning-hub/money-foundations/lesson-07.png",
        youtubeId: "Pd3HYjpmks4",
        sourceUrl: "https://www.youtube.com/watch?v=Pd3HYjpmks4&t=17s",
      },
      {
        id: "the-rich-play-a-different-game",
        lessonNumber: 8,
        title: "The Rich Play a Different Game",
        subtitle: "Wealth grows through ownership, strategy, and long-term thinking.",
        thumbnail: "/learning-hub/money-foundations/lesson-08.png",
        youtubeId: "BLBRRNwMZNE",
        sourceUrl: "https://www.youtube.com/watch?v=BLBRRNwMZNE&t=91s",
      },
      {
        id: "make-more-not-just-save-more",
        lessonNumber: 9,
        title: "Make More, Not Just Save More",
        subtitle: "Growing income expands what saving alone cannot.",
        thumbnail: "/learning-hub/money-foundations/lesson-09.png",
        youtubeId: "q24L2j4sq04",
        sourceUrl: "https://www.youtube.com/watch?v=q24L2j4sq04",
      },
      {
        id: "read-money-books-extract-rules",
        lessonNumber: 10,
        title: "Read Money Books, Extract Rules",
        subtitle: "Turn good ideas into practical money rules you can actually follow.",
        thumbnail: "/learning-hub/money-foundations/lesson-10.png",
        youtubeId: "uWWEodOlDGk",
        sourceUrl: "https://www.youtube.com/watch?v=uWWEodOlDGk&t=2s",
      },
    ],
  },
  {
    id: "video",
    type: "video",
    title: "CLARA Money Masterclass",
    subtitle: "Build your personal finance foundation step by step.",
    description: "A guided video series that teaches money awareness, income, cash flow, budgeting, spending discipline, emergency protection, debt, saving, and long-term direction.",
    order: 1,
    ctaLabel: "Start masterclass",
  },
  {
    id: "book",
    type: "book",
    title: "Books & Guides",
    subtitle: "Read deeper CLARA lessons.",
    description: "Use CLARA guides when you want a slower, deeper explanation of each money system.",
    order: 2,
    ctaLabel: "See all guides",
  },
  {
    id: "practice",
    type: "practice",
    title: "Practice Tools",
    subtitle: "Apply what you learned with guided money exercises.",
    description: "Turn lessons into small guided money decisions and checks.",
    order: 3,
    ctaLabel: "See all tools",
  },
  {
    id: "game",
    type: "game",
    title: "Money Games",
    subtitle: "Train your financial decisions through simple money games.",
    description: "Practice decisions in a low-pressure, interactive way.",
    order: 4,
    ctaLabel: "See all games",
  },
  {
    id: "challenge",
    type: "challenge",
    title: "Challenges",
    subtitle: "Build financial discipline through small guided actions.",
    description: "Use short challenges to turn financial awareness into daily behavior.",
    order: 5,
    ctaLabel: "See all challenges",
  },
];

export const learningHubData = [
  {
    id: "money-feels-gone-video",
    type: "video",
    category: "video",
    title: "Why Your Money Feels Gone",
    subtitle: "Understand the payday disappearance pattern before trying to fix it.",
    description: "Episode 1 of the CLARA Money Masterclass. Learn why money can feel gone even when income just arrived.",
    status: "available",
    embedUrl: "https://www.youtube.com/embed/jTcO476xQ4Y?rel=0&modestbranding=1&playsinline=1&controls=1&fs=1",
    externalUrl: "https://youtu.be/jTcO476xQ4Y?si=HpjwZEoPO0s7jnm0",
    provider: "youtube",
    featured: true,
    order: 1,
    duration: "6 min",
    coverLabel: "Episode 01",
    tags: ["awareness", "payday", "money behavior"],
  },
  {
    id: "know-your-real-income-video",
    type: "video",
    category: "video",
    title: "Know Your Real Income",
    subtitle: "See what you actually earn, how often it comes, and how stable it is.",
    description: "Episode 2 of the CLARA Money Masterclass. Learn the difference between income received and income you can safely plan around.",
    status: "coming-soon",
    order: 2,
    duration: "7 min",
    coverLabel: "Episode 02",
    tags: ["income", "stability", "planning"],
  },
  {
    id: "cash-flow-how-money-moves-video",
    type: "video",
    category: "video",
    title: "Cash Flow: How Money Moves",
    subtitle: "Follow your money from payday to bills, spending, saving, and pressure points.",
    description: "Episode 3 of the CLARA Money Masterclass. Understand how money moves through your month and why timing matters.",
    status: "coming-soon",
    order: 3,
    duration: "8 min",
    coverLabel: "Episode 03",
    tags: ["cash flow", "payday cycle", "money movement"],
  },
  {
    id: "bills-first-video",
    type: "video",
    category: "video",
    title: "Bills First",
    subtitle: "Protect essentials before wants compete for your money.",
    description: "Episode 4 of the CLARA Money Masterclass. Learn why essentials, due dates, and survival expenses must come first.",
    status: "coming-soon",
    order: 4,
    duration: "6 min",
    coverLabel: "Episode 04",
    tags: ["bills", "essentials", "priority"],
  },
  {
    id: "wallet-system-video",
    type: "video",
    category: "video",
    title: "Wallet System",
    subtitle: "Give your money a place before it gets spent accidentally.",
    description: "Episode 5 of the CLARA Money Masterclass. Learn how separated wallets create boundaries, clarity, and discipline.",
    status: "coming-soon",
    order: 5,
    duration: "7 min",
    coverLabel: "Episode 05",
    tags: ["wallets", "organization", "money system"],
  },
  {
    id: "budget-that-fits-real-life-video",
    type: "video",
    category: "video",
    title: "Budget That Fits Real Life",
    subtitle: "Build a budget that guides your money without feeling like punishment.",
    description: "Episode 6 of the CLARA Money Masterclass. Learn how to build realistic budget categories and adjust with real life.",
    status: "coming-soon",
    order: 6,
    duration: "8 min",
    coverLabel: "Episode 06",
    tags: ["budget", "planning", "real life"],
  },
  {
    id: "ask-before-you-spend-video",
    type: "video",
    category: "video",
    title: "Ask Before You Spend",
    subtitle: "Pause before your wallet reacts to emotion, pressure, or impulse.",
    description: "Episode 7 of the CLARA Money Masterclass. Learn CLARA’s signature habit for checking if spending fits your real life.",
    status: "coming-soon",
    order: 7,
    duration: "7 min",
    coverLabel: "Episode 07",
    tags: ["spending", "discipline", "pause"],
  },
  {
    id: "emergency-fund-video",
    type: "video",
    category: "video",
    title: "Emergency Fund",
    subtitle: "Build protection before pressure forces you to borrow.",
    description: "Episode 8 of the CLARA Money Masterclass. Learn why emergency money is protection, not just extra savings.",
    status: "coming-soon",
    order: 8,
    duration: "7 min",
    coverLabel: "Episode 08",
    tags: ["emergency fund", "protection", "buffer"],
  },
  {
    id: "debt-and-obligations-video",
    type: "video",
    category: "video",
    title: "Debt & Obligations",
    subtitle: "See what your income already owes before making new money decisions.",
    description: "Episode 9 of the CLARA Money Masterclass. Learn how debt, due dates, minimum payments, and obligations affect financial freedom.",
    status: "coming-soon",
    order: 9,
    duration: "8 min",
    coverLabel: "Episode 09",
    tags: ["debt", "obligations", "pressure"],
  },
  {
    id: "saving-goals-wealth-direction-video",
    type: "video",
    category: "video",
    title: "Saving, Goals, and Wealth Direction",
    subtitle: "Move from surviving the month to building visible progress.",
    description: "Episode 10 of the CLARA Money Masterclass. Learn how saving, goal clarity, consistency, and long-term direction work together.",
    status: "coming-soon",
    order: 10,
    duration: "9 min",
    coverLabel: "Episode 10",
    tags: ["saving", "goals", "wealth direction"],
  },
  {
    id: "income-hub",
    title: "Income Hub",
    subtitle: "Understand where your money comes from",
    type: "book",
    category: "book",
    status: "available",
    featured: true,
    order: 1,
    accent: "cyan",
    coverLabel: "Money Source",
    coverImage: "images/learning-hub/income-hub.webp.png",
    thumbnail: "images/learning-hub/income-hub.webp.png",
    tags: ["income", "stability", "starting point"],
    pdfParts: [
      {
        id: "part-1",
        path: "/books/so-thats-it/clara-so-thats-it-part-1-pages-1-31.pdf",
        startPage: 1,
        endPage: 31,
        expectedPageCount: 31,
      },
      {
        id: "part-2",
        path: "/books/so-thats-it/clara-so-thats-it-part-2-pages-32-52.pdf",
        startPage: 32,
        endPage: 52,
        expectedPageCount: 21,
      },
    ],
    totalPages: 52,
    pages: [
      {
        title: "The Reality",
        body: "Before you can manage money well, you need to understand where your money comes from and how stable it really is.",
      },
      {
        title: "The Pattern",
        body: "Income can come from salary, side income, freelance work, business, support, or irregular sources. Not all income has the same reliability.",
      },
      {
        title: "The Move",
        body: "List every income source, how often it comes, and how stable it is. CLARA uses this to understand your financial starting point.",
      },
      {
        title: "Grow the Source",
        body: "Income growth can come from upskilling, better work, side projects, business, or improving consistency. More income should create more direction, not just more spending.",
      },
      {
        title: "CLARA Application",
        body: "Income Hub helps CLARA see your money source, income rhythm, and earning stability before giving financial guidance.",
      },
    ],
  },
  {
    id: "wallet-hub",
    title: "Wallet Hub",
    subtitle: "Organize money by purpose",
    type: "book",
    category: "book",
    status: "available",
    order: 2,
    accent: "teal",
    coverLabel: "Money System",
    coverImage: "images/learning-hub/wallet-hub.webp.png",
    thumbnail: "images/learning-hub/wallet-hub.webp.png",
    tags: ["wallets", "organization", "purpose"],
    pages: [
      {
        title: "The Reality",
        body: "A wallet is not just a place where money sits. It can become a boundary that tells your money what it is allowed to do.",
      },
      {
        title: "The Pattern",
        body: "When all money is mixed together, bills, savings, spending, and goals can blur. Money with no clear purpose is easier to spend accidentally.",
      },
      {
        title: "The Move",
        body: "Create wallets for specific purposes such as daily spending, bills, savings, emergency fund, and goals.",
      },
      {
        title: "Psychology of Wallets",
        body: "A designated wallet makes money feel assigned. Savings money feels less touchable when it is separated from spending money.",
      },
      {
        title: "CLARA Application",
        body: "Wallet Hub helps CLARA understand how your money is separated, protected, and prepared for real-life use.",
      },
    ],
  },
  {
    id: "budget-hub",
    title: "Budget Hub",
    subtitle: "Give your money clear direction",
    type: "book",
    category: "book",
    status: "available",
    order: 3,
    accent: "emerald",
    coverLabel: "Money Plan",
    coverImage: "images/learning-hub/budget-hub.webp.png",
    thumbnail: "images/learning-hub/budget-hub.webp.png",
    tags: ["budget", "plan", "direction"],
    pages: [
      {
        title: "The Reality",
        body: "A budget is not punishment. It is a direction for your money before emotion, pressure, and habits decide for you.",
      },
      {
        title: "The Pattern",
        body: "Budgets often fail when they are too strict, unrealistic, outdated, or disconnected from real spending behavior.",
      },
      {
        title: "The Move",
        body: "Build budget categories for bills, food, transport, debt, savings, family support, and safe spending.",
      },
      {
        title: "Realistic Budgeting",
        body: "A strong budget should adjust with real life. The goal is not perfection, but honest control.",
      },
      {
        title: "CLARA Application",
        body: "Budget Hub helps CLARA compare your plan with your actual behavior so you can see where money is following or breaking the plan.",
      },
    ],
  },
  {
    id: "emergency-fund",
    title: "Emergency Fund",
    subtitle: "Build protection before pressure hits",
    type: "book",
    category: "book",
    status: "available",
    order: 4,
    accent: "teal",
    coverLabel: "Protection",
    coverImage: "images/learning-hub/emergency-fund.webp.png",
    thumbnail: "images/learning-hub/emergency-fund.webp.png",
    tags: ["emergency fund", "protection", "buffer"],
    pages: [
      {
        title: "The Reality",
        body: "An emergency fund is protection money. It helps you handle urgent needs without immediately depending on debt.",
      },
      {
        title: "The Pattern",
        body: "Without a buffer, one medical need, family emergency, lost workday, delayed income, or repair can disturb the whole month.",
      },
      {
        title: "The Move",
        body: "Start with a small target and build consistently. Protection grows through repeated deposits, not one perfect amount.",
      },
      {
        title: "Emergency or Not",
        body: "Not every pressure is an emergency. Separate true urgent needs from cravings, wants, and emotional spending.",
      },
      {
        title: "CLARA Application",
        body: "Emergency Fund helps CLARA understand how protected you are when life suddenly becomes expensive.",
      },
    ],
  },
  {
    id: "savings-goals",
    title: "Savings Goals",
    subtitle: "Turn saving into visible progress",
    type: "book",
    category: "book",
    status: "available",
    order: 5,
    accent: "blue",
    coverLabel: "Money Progress",
    coverImage: "images/learning-hub/savings-goals.webp.png",
    thumbnail: "images/learning-hub/savings-goals.webp.png",
    tags: ["saving", "goals", "progress"],
    pages: [
      {
        title: "The Reality",
        body: "Saving becomes easier when money has a clear destination. A goal gives your money emotional meaning.",
      },
      {
        title: "The Pattern",
        body: "Without a target, saving can feel vague. Money that is only “extra” often gets spent before it becomes progress.",
      },
      {
        title: "The Move",
        body: "Define the goal amount, deadline, reason, and regular contribution. Break the target into smaller payday or monthly steps.",
      },
      {
        title: "Protect the Goal",
        body: "Do not mix goal money with daily spending. A savings goal should be protected from impulse and temporary emotions.",
      },
      {
        title: "CLARA Application",
        body: "Savings Goals helps CLARA show progress, not just balance, so users can see that small consistent saving is moving somewhere.",
      },
    ],
  },
  {
    id: "debt-obligations",
    title: "Debt / Obligations",
    subtitle: "See what your income already owes",
    type: "book",
    category: "book",
    status: "available",
    order: 6,
    accent: "rose",
    coverLabel: "Money Pressure",
    coverImage: "images/learning-hub/debt-obligations.webp.png",
    thumbnail: "images/learning-hub/debt-obligations.webp.png",
    tags: ["debt", "obligations", "pressure"],
    pages: [
      {
        title: "The Reality",
        body: "Debt and obligations are money commitments that already have a claim on your future income.",
      },
      {
        title: "The Pattern",
        body: "Debt feels heavy when due dates, balances, minimum payments, interest, family obligations, and recurring commitments are unclear.",
      },
      {
        title: "The Move",
        body: "List every obligation with the amount, due date, minimum payment, and priority. Visibility reduces panic.",
      },
      {
        title: "Recovery Direction",
        body: "Keep minimum payments active, focus extra money on one priority, and avoid adding new debt while recovering.",
      },
      {
        title: "CLARA Application",
        body: "Debt / Obligations helps CLARA understand how much of your income is already committed before recommending spending, saving, or budgeting moves.",
      },
    ],
  },
  {
    id: "budget-fit-checker",
    type: "practice",
    category: "practice",
    title: "Budget Fit Checker",
    subtitle: "Check if a purchase fits your real budget before spending.",
    description:
      "A guided practice tool that compares a spending idea against your budget room, wallet balance, and priority needs.",
    status: "coming-soon",
    order: 1,
    coverLabel: "Practice Tool",
    tags: ["budget", "spending check", "practice"],
  },
  {
    id: "payday-leak-finder",
    type: "practice",
    category: "practice",
    title: "Payday Leak Finder",
    subtitle: "Find where your salary usually disappears first.",
    description:
      "A guided exercise for spotting the first leaks after income arrives.",
    status: "coming-soon",
    order: 2,
    coverLabel: "Practice Tool",
    tags: ["payday", "cash flow", "awareness"],
  },
  {
    id: "bills-first-sorter",
    type: "practice",
    category: "practice",
    title: "Bills First Sorter",
    subtitle: "Sort essentials before flexible spending.",
    description:
      "A simple guided sorter that helps users separate must-pay items from optional spending.",
    status: "coming-soon",
    order: 3,
    coverLabel: "Practice Tool",
    tags: ["bills", "priority", "essentials"],
  },
  {
    id: "survive-until-payday",
    type: "game",
    category: "game",
    title: "Survive Until Payday",
    subtitle: "Make decisions that keep your money alive until the next income date.",
    description:
      "A simple decision game where every choice affects your money left before payday.",
    status: "coming-soon",
    order: 1,
    coverLabel: "Money Game",
    tags: ["payday", "decision", "game"],
  },
  {
    id: "needs-vs-wants",
    type: "game",
    category: "game",
    title: "Needs vs Wants",
    subtitle: "Train your ability to separate essentials from desires.",
    description:
      "A fast sorting game for recognizing needs, wants, and emotional pressure.",
    status: "coming-soon",
    order: 2,
    coverLabel: "Money Game",
    tags: ["needs", "wants", "discipline"],
  },
  {
    id: "budget-battle",
    type: "game",
    category: "game",
    title: "Budget Battle",
    subtitle: "Protect your budget while real-life expenses compete for space.",
    description:
      "A money decision game about tradeoffs, limits, and priority spending.",
    status: "coming-soon",
    order: 3,
    coverLabel: "Money Game",
    tags: ["budget", "tradeoffs", "game"],
  },
  {
    id: "impulse-monster",
    type: "game",
    category: "game",
    title: "Impulse Monster",
    subtitle: "Beat quick urges before they eat your wallet.",
    description:
      "A playful game about recognizing impulse triggers before they become expenses.",
    status: "coming-soon",
    order: 4,
    coverLabel: "Money Game",
    tags: ["impulse", "emotion", "spending"],
  },
  {
    id: "emergency-hit",
    type: "game",
    category: "game",
    title: "Emergency Hit",
    subtitle: "See how protection money changes the outcome when life hits.",
    description:
      "A scenario game showing why emergency buffers matter.",
    status: "coming-soon",
    order: 5,
    coverLabel: "Money Game",
    tags: ["emergency", "buffer", "protection"],
  },
  {
    id: "three-day-spend-awareness",
    type: "challenge",
    category: "challenge",
    title: "3-Day Spend Awareness Challenge",
    subtitle: "Notice every peso before trying to change everything.",
    description:
      "A short challenge focused on awareness before correction.",
    status: "coming-soon",
    order: 1,
    coverLabel: "Challenge",
    tags: ["awareness", "tracking", "discipline"],
  },
  {
    id: "seven-day-ask-before-spend",
    type: "challenge",
    category: "challenge",
    title: "7-Day Ask Before You Spend Challenge",
    subtitle: "Build the habit of checking first before spending.",
    description:
      "A week-long behavior challenge built around CLARA's Ask Before You Spend habit.",
    status: "coming-soon",
    order: 2,
    coverLabel: "Challenge",
    tags: ["ask before you spend", "habit", "discipline"],
  },
  {
    id: "bills-first-challenge",
    type: "challenge",
    category: "challenge",
    title: "Bills First Challenge",
    subtitle: "Protect essentials before money becomes flexible.",
    description:
      "A guided challenge for prioritizing essentials before wants.",
    status: "coming-soon",
    order: 3,
    coverLabel: "Challenge",
    tags: ["bills", "essentials", "priority"],
  },
  {
    id: "no-random-spending-weekend",
    type: "challenge",
    category: "challenge",
    title: "No Random Spending Weekend",
    subtitle: "Avoid unplanned spending for one weekend.",
    description:
      "A small weekend challenge to practice discipline without overcomplicating the month.",
    status: "coming-soon",
    order: 4,
    coverLabel: "Challenge",
    tags: ["spending", "weekend", "discipline"],
  },
  {
    id: "emergency-fund-starter-challenge",
    type: "challenge",
    category: "challenge",
    title: "Emergency Fund Starter Challenge",
    subtitle: "Start protection with one small committed move.",
    description:
      "A beginner challenge for creating the first emergency fund action.",
    status: "coming-soon",
    order: 5,
    coverLabel: "Challenge",
    tags: ["emergency fund", "saving", "protection"],
  },
];
