export const learningHubCategories = [
  {
    id: "video",
    type: "video",
    title: "CLARA Money Masterclass",
    subtitle: "Build your personal finance foundation step by step.",
    description: "A guided video series that teaches money awareness, income, cash flow, budgeting, spending discipline, emergency protection, debt, saving, and long-term direction.",
    order: 1,
    ctaLabel: "Start masterclass",
  },
  {
    id: "book",
    type: "book",
    title: "Books & Guides",
    subtitle: "Read deeper CLARA lessons.",
    description: "Use CLARA guides when you want a slower, deeper explanation of each money system.",
    order: 2,
    ctaLabel: "See all guides",
  },
  {
    id: "practice",
    type: "practice",
    title: "Practice Tools",
    subtitle: "Apply what you learned with guided money exercises.",
    description: "Turn lessons into small guided money decisions and checks.",
    order: 3,
    ctaLabel: "See all tools",
  },
  {
    id: "game",
    type: "game",
    title: "Money Games",
    subtitle: "Train your financial decisions through simple money games.",
    description: "Practice decisions in a low-pressure, interactive way.",
    order: 4,
    ctaLabel: "See all games",
  },
  {
    id: "challenge",
    type: "challenge",
    title: "Challenges",
    subtitle: "Build financial discipline through small guided actions.",
    description: "Use short challenges to turn financial awareness into daily behavior.",
    order: 5,
    ctaLabel: "See all challenges",
  },
];

export const learningHubData = [
  {
    id: "money-feels-gone-video",
    type: "video",
    category: "video",
    title: "Why Your Money Feels Gone",
    subtitle: "Understand the payday disappearance pattern before trying to fix it.",
    description: "Episode 1 of the CLARA Money Masterclass. Learn why money can feel gone even when income just arrived.",
    status: "available",
    embedUrl: "https://www.youtube.com/embed/jTcO476xQ4Y?rel=0&modestbranding=1&playsinline=1&controls=1&fs=1",
    externalUrl: "https://youtu.be/jTcO476xQ4Y?si=HpjwZEoPO0s7jnm0",
    provider: "youtube",
    featured: true,
    order: 1,
    duration: "6 min",
    coverLabel: "Episode 01",
    tags: ["awareness", "payday", "money behavior"],
  },
  {
    id: "know-your-real-income-video",
    type: "video",
    category: "video",
    title: "Know Your Real Income",
    subtitle: "See what you actually earn, how often it comes, and how stable it is.",
    description: "Episode 2 of the CLARA Money Masterclass. Learn the difference between income received and income you can safely plan around.",
    status: "coming-soon",
    order: 2,
    duration: "7 min",
    coverLabel: "Episode 02",
    tags: ["income", "stability", "planning"],
  },
  {
    id: "cash-flow-how-money-moves-video",
    type: "video",
    category: "video",
    title: "Cash Flow: How Money Moves",
    subtitle: "Follow your money from payday to bills, spending, saving, and pressure points.",
    description: "Episode 3 of the CLARA Money Masterclass. Understand how money moves through your month and why timing matters.",
    status: "coming-soon",
    order: 3,
    duration: "8 min",
    coverLabel: "Episode 03",
    tags: ["cash flow", "payday cycle", "money movement"],
  },
  {
    id: "bills-first-video",
    type: "video",
    category: "video",
    title: "Bills First",
    subtitle: "Protect essentials before wants compete for your money.",
    description: "Episode 4 of the CLARA Money Masterclass. Learn why essentials, due dates, and survival expenses must come first.",
    status: "coming-soon",
    order: 4,
    duration: "6 min",
    coverLabel: "Episode 04",
    tags: ["bills", "essentials", "priority"],
  },
  {
    id: "wallet-system-video",
    type: "video",
    category: "video",
    title: "Wallet System",
    subtitle: "Give your money a place before it gets spent accidentally.",
    description: "Episode 5 of the CLARA Money Masterclass. Learn how separated wallets create boundaries, clarity, and discipline.",
    status: "coming-soon",
    order: 5,
    duration: "7 min",
    coverLabel: "Episode 05",
    tags: ["wallets", "organization", "money system"],
  },
  {
    id: "budget-that-fits-real-life-video",
    type: "video",
    category: "video",
    title: "Budget That Fits Real Life",
    subtitle: "Build a budget that guides your money without feeling like punishment.",
    description: "Episode 6 of the CLARA Money Masterclass. Learn how to build realistic budget categories and adjust with real life.",
    status: "coming-soon",
    order: 6,
    duration: "8 min",
    coverLabel: "Episode 06",
    tags: ["budget", "planning", "real life"],
  },
  {
    id: "ask-before-you-spend-video",
    type: "video",
    category: "video",
    title: "Ask Before You Spend",
    subtitle: "Pause before your wallet reacts to emotion, pressure, or impulse.",
    description: "Episode 7 of the CLARA Money Masterclass. Learn CLARA’s signature habit for checking if spending fits your real life.",
    status: "coming-soon",
    order: 7,
    duration: "7 min",
    coverLabel: "Episode 07",
    tags: ["spending", "discipline", "pause"],
  },
  {
    id: "emergency-fund-video",
    type: "video",
    category: "video",
    title: "Emergency Fund",
    subtitle: "Build protection before pressure forces you to borrow.",
    description: "Episode 8 of the CLARA Money Masterclass. Learn why emergency money is protection, not just extra savings.",
    status: "coming-soon",
    order: 8,
    duration: "7 min",
    coverLabel: "Episode 08",
    tags: ["emergency fund", "protection", "buffer"],
  },
  {
    id: "debt-and-obligations-video",
    type: "video",
    category: "video",
    title: "Debt & Obligations",
    subtitle: "See what your income already owes before making new money decisions.",
    description: "Episode 9 of the CLARA Money Masterclass. Learn how debt, due dates, minimum payments, and obligations affect financial freedom.",
    status: "coming-soon",
    order: 9,
    duration: "8 min",
    coverLabel: "Episode 09",
    tags: ["debt", "obligations", "pressure"],
  },
  {
    id: "saving-goals-wealth-direction-video",
    type: "video",
    category: "video",
    title: "Saving, Goals, and Wealth Direction",
    subtitle: "Move from surviving the month to building visible progress.",
    description: "Episode 10 of the CLARA Money Masterclass. Learn how saving, goal clarity, consistency, and long-term direction work together.",
    status: "coming-soon",
    order: 10,
    duration: "9 min",
    coverLabel: "Episode 10",
    tags: ["saving", "goals", "wealth direction"],
  },
  {
    id: "income-hub",
    title: "Income Hub",
    subtitle: "Understand where your money comes from",
    type: "book",
    category: "book",
    status: "available",
    featured: true,
    order: 1,
    accent: "cyan",
    coverLabel: "Money Source",
    coverImage: "images/learning-hub/income-hub.webp.png",
    thumbnail: "images/learning-hub/income-hub.webp.png",
    tags: ["income", "stability", "starting point"],
    pdfParts: [
      {
        id: "part-1",
        path: "/books/so-thats-it/clara-so-thats-it-part-1-pages-1-31.pdf",
        startPage: 1,
        endPage: 31,
        expectedPageCount: 31,
      },
      {
        id: "part-2",
        path: "/books/so-thats-it/clara-so-thats-it-part-2-pages-32-52.pdf",
        startPage: 32,
        endPage: 52,
        expectedPageCount: 21,
      },
    ],
    totalPages: 52,
    pages: [
      {
        title: "The Reality",
        body: "Before you can manage money well, you need to understand where your money comes from and how stable it really is.",
      },
      {
        title: "The Pattern",
        body: "Income can come from salary, side income, freelance work, business, support, or irregular sources. Not all income has the same reliability.",
      },
      {
        title: "The Move",
        body: "List every income source, how often it comes, and how stable it is. CLARA uses this to understand your financial starting point.",
      },
      {
        title: "Grow the Source",
        body: "Income growth can come from upskilling, better work, side projects, business, or improving consistency. More income should create more direction, not just more spending.",
      },
      {
        title: "CLARA Application",
        body: "Income Hub helps CLARA see your money source, income rhythm, and earning stability before giving financial guidance.",
      },
    ],
  },
  {
    id: "wallet-hub",
    title: "Wallet Hub",
    subtitle: "Organize money by purpose",
    type: "book",
    category: "book",
    status: "available",
    order: 2,
    accent: "teal",
    coverLabel: "Money System",
    coverImage: "images/learning-hub/wallet-hub.webp.png",
    thumbnail: "images/learning-hub/wallet-hub.webp.png",
    tags: ["wallets", "organization", "purpose"],
    pages: [
      {
        title: "The Reality",
        body: "A wallet is not just a place where money sits. It can become a boundary that tells your money what it is allowed to do.",
      },
      {
        title: "The Pattern",
        body: "When all money is mixed together, bills, savings, spending, and goals can blur. Money with no clear purpose is easier to spend accidentally.",
      },
      {
        title: "The Move",
        body: "Create wallets for specific purposes such as daily spending, bills, savings, emergency fund, and goals.",
      },
      {
        title: "Psychology of Wallets",
        body: "A designated wallet makes money feel assigned. Savings money feels less touchable when it is separated from spending money.",
      },
      {
        title: "CLARA Application",
        body: "Wallet Hub helps CLARA understand how your money is separated, protected, and prepared for real-life use.",
      },
    ],
  },
  {
    id: "budget-hub",
    title: "Budget Hub",
    subtitle: "Give your money clear direction",
    type: "book",
    category: "book",
    status: "available",
    order: 3,
    accent: "emerald",
    coverLabel: "Money Plan",
    coverImage: "images/learning-hub/budget-hub.webp.png",
    thumbnail: "images/learning-hub/budget-hub.webp.png",
    tags: ["budget", "plan", "direction"],
    pages: [
      {
        title: "The Reality",
        body: "A budget is not punishment. It is a direction for your money before emotion, pressure, and habits decide for you.",
      },
      {
        title: "The Pattern",
        body: "Budgets often fail when they are too strict, unrealistic, outdated, or disconnected from real spending behavior.",
      },
      {
        title: "The Move",
        body: "Build budget categories for bills, food, transport, debt, savings, family support, and safe spending.",
      },
      {
        title: "Realistic Budgeting",
        body: "A strong budget should adjust with real life. The goal is not perfection, but honest control.",
      },
      {
        title: "CLARA Application",
        body: "Budget Hub helps CLARA compare your plan with your actual behavior so you can see where money is following or breaking the plan.",
      },
    ],
  },
  {
    id: "emergency-fund",
    title: "Emergency Fund",
    subtitle: "Build protection before pressure hits",
    type: "book",
    category: "book",
    status: "available",
    order: 4,
    accent: "teal",
    coverLabel: "Protection",
    coverImage: "images/learning-hub/emergency-fund.webp.png",
    thumbnail: "images/learning-hub/emergency-fund.webp.png",
    tags: ["emergency fund", "protection", "buffer"],
    pages: [
      {
        title: "The Reality",
        body: "An emergency fund is protection money. It helps you handle urgent needs without immediately depending on debt.",
      },
      {
        title: "The Pattern",
        body: "Without a buffer, one urgent event can force borrowing, delay bills, or break your budget.",
      },
      {
        title: "The Move",
        body: "Start by building at least one month of survival expenses, then grow toward three to six months over time.",
      },
      {
        title: "When to Use It",
        body: "Use emergency money only for urgent, necessary, and unexpected situations — not for lifestyle upgrades or emotional spending.",
      },
      {
        title: "CLARA Application",
        body: "Emergency Fund helps CLARA understand your protection level and whether a spending decision puts your stability at risk.",
      },
    ],
  },
  {
    id: "spending-diagnosis",
    title: "Spending Diagnosis",
    subtitle: "Ask before you spend",
    type: "book",
    category: "book",
    status: "available",
    order: 5,
    accent: "violet",
    coverLabel: "Spend Check",
    coverImage: "images/learning-hub/spending-diagnosis.webp.png",
    thumbnail: "images/learning-hub/spending-diagnosis.webp.png",
    tags: ["spending", "decision", "clarity"],
    pages: [
      {
        title: "The Reality",
        body: "Spending is not only math. Sometimes it is emotion, stress, pressure, convenience, or habit moving faster than wisdom.",
      },
      {
        title: "The Pattern",
        body: "Many purchases feel small in the moment, but repeated unchecked spending can quietly weaken your financial stability.",
      },
      {
        title: "The Move",
        body: "Before spending, ask whether the purchase is necessary, planned, affordable, emotionally driven, and aligned with your current priorities.",
      },
      {
        title: "Safe Spending",
        body: "Safe spending means the purchase does not damage bills, savings, emergency protection, or your ability to survive until the next income.",
      },
      {
        title: "CLARA Application",
        body: "Spending Diagnosis helps CLARA act like a pause button between impulse and action so your money decisions become more intentional.",
      },
    ],
  },
];
